### ISSUE TITLE
nextjs ：SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by woloxi** [greensock/react#1]
Hello, I encountered an issue with the console error while using useGSAP in Next.js. Could you please help me .thank you.

nextjs：13.5.6

code：

import React, { useRef, useEffect } from 'react';
import { useTranslation } from 'next-i18next';

import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

function Banner() {
  const container = useRef<HTMLDivElement>(null);

  useGSAP(
    () => {
     
    },
    [],
    container,
  );

  const { t } = useTranslation(['home', 'path']);
  const TPArrData = [t('banner-tp-评价-1'), t('banner-tp-评价-2'), t('banner-tp-评价-3')];

  return (
    <section
      ref={container}
      className="box container relative mt-20 grid grid-cols-1 opacity-0 md:mt-[102px] lg:mt-[150px] lg:grid-cols-2 lg:gap-7"
    />
  );
}

export default Banner;

Error：
node_modules/@gsap/react/src/index.js:11
import { useEffect, useLayoutEffect } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)

**Comment by rhernandog** [comment]
Hi @woloxi,

Thanks for reporting this. I haven't been able to reproduce this on my local environment but the idea in this case would be to change the `next.config.js` file in order to use the Transpile Pacjages config option in order to tell Next to transpile the `@gsap/react` package to prevent this error from happening:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ["@gsap/react"],
};

module.exports = nextConfig;
```
You can see a live minimal demo here:
[https://stackblitz.com/edit/stackblitz-starters-lhcjkn](https://stackblitz.com/edit/stackblitz-starters-lhcjkn?description=The%20React%20framework%20for%20production&file=package-lock.json,next.config.js%3AL7&title=Next.js%20Starter)

Please let us know how this works.

Happy Tweening!

**Comment by woloxi** [comment]
Hi @rhernandog,

Thank you so much ! I implemented the changes you suggested in the `next.config.js` file using the `transpilePackages` option.

**Comment by rhernandog** [comment]
Hi @woloxi,

Did the suggested changes worked as expected?

Please let us know so we can close this as resolved.

Happy Tweening!

**Comment by rhernandog** [comment]
Hi again @woloxi!

We pushed a few updates in the hook, which is including a UMD module of it as well. As you can see in this demo, is no longer necessary to update the `next.config.js` file in order to make it work, although keeping said configuration won't cause any problems.

https://stackblitz.com/edit/stackblitz-starters-3zkguu

Happy Tweening!
