### ISSUE TITLE
The requested module '@gsap/react' is a CommonJS module

### ISSUE THREAD

**Issue by PaulieScanlon** [greensock/react#2]
Hi team. I was giving this a try as per this [Twitter/X suggeston](https://twitter.com/greensock/status/1732670646373515774), and I'm using Remix so i think this is related to ESM, here's the error i get. 

```
import { useGSAP } from "@gsap/react";
         ^^^^^^^
SyntaxError: Named export 'useGSAP' not found. The requested module '@gsap/react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@gsap/react';
const { useGSAP } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
    at run (/Users/paulscanlon/Documents/Paulie/Dev Live/Punk Squirrel/development/punk-squirrel/node_modules/@remix-run/serve/dist/cli.js:98:15)
```

**Comment by jackdoyle** [comment]
Howdy, @PaulieScanlon 

That message is a bit confusing because the useGSAP() hook is just a regular ES Module and it definitely has a named "useGSAP" export (feel free to check the source). I'm completely unfamiliar with Remix, sorry. I did just push up version 2.0.1 that includes a UMD version in the /dist/ directory in case you want to try to import from there instead. Does that work any better in your environment?

**Comment by rhernandog** [comment]
Hi @PaulieScanlon,

We created a minimal demo with a setup with the latest version of the useGSAP hook on a Remix app, created with the latest version of Remix:

https://stackblitz.com/edit/remix-run-remix-3bjuv1?file=app%2Froot.tsx

Just run
```
npx create-remix@latest
npm i -s gsap @gsap/react
```
And it should work as expected.

Please let us know how this works.
Happy Tweening!
