### ISSUE TITLE
Use latest gsap version?

### ISSUE THREAD

**Issue by Twansparant** [greensock/react#5]
Hi there,

I'm using this package as well as the normal `gsap` package and have installed it following the instructions [here](https://gsap.com/docs/v3/Installation/?tab=npm&module=esm&method=private+registry&tier=free&club=true&require=false&trial=true).

```json
"dependencies": {
    "@gsap/react": "^2.1.0",
    "gsap": "npm:@gsap/shockingly@^3.12.5"
}
```

Using the above `package.json`, **gsap** version always returns `3.12.4`:
I see the latest `@gsap/react` version has a dependency of `"gsap": "^3.12.4"`;

Is there no way to use the latest version in pair with this package?
I cleared the `npm cache`, deleted `node_modules`, `package-lock` etc and even rebuild my whole docker images, but it still uses version `3.12.4`.

Thanks!

**Comment by jackdoyle** [comment]
I'm not an expert on that, but it sounds strange because "^3.12.4" should indeed resolve to the latest 3.12.5. Your build system should recognize that, but I wonder if you're using something that doesn't resolve things that way? I mean gsap is just a dependency of the @gsap/react package, so it should resolve those dependencies according to the way I mentioned above (but again, I'm not an expert). I wonder if anyone else has any insights to share here. 

@Twansparant did you try registering your useGSAP hook like this?: 
```javascript
gsap.registerPlugin(useGSAP);
```

And does that make any difference?

**Comment by Twansparant** [comment]
> @Twansparant did you try registering your useGSAP hook like this?:

I didn't, but I just added that to my files without any difference I'm afraid...
However, I did a fresh install of the repo with a clean install of the `node_modules` and that did the trick in the end.
Sorry for the confusion!
